name: continuous-integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - run: haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git
      - run: haxelib git haxeui-html5 https://github.com/haxeui/haxeui-html5.git
      - run: haxe html5.hxml
      - run: cp -a /build/html5/. /docs/

