name: continuous-integration
on: push
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - run: haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git
      - run: haxelib git haxeui-html5 https://github.com/haxeui/haxeui-html5.git
      - run: haxelib git haxeui-heaps https://github.com/haxeui/haxeui-heaps.git
      - run: haxelib git haxeui-heaps https://github.com/haxeui/haxeui-nme.git
      - run: haxelib git haxeui-heaps https://github.com/haxeui/haxeui-openfl.git
      - run: haxelib git heaps https://github.com/HeapsIO/heaps.git
      - run: haxelib install lime 
      - run: haxelib install openfl 
      - run: haxelib install nme 

      - run: haxe html5.hxml
      - run: haxe html5.buttons.from.externs.hxml
      - run: haxe html5.labels.from.externs.hxml
      - run: haxe html5.host.hxml
      - run: cp -a build/html5/. docs/html5/
      - run: haxe heaps-js.hxml
      - run: cp -a build/heaps/js/. docs/heaps-js/
      - run: haxelib run openfl build html5
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

