jobs:
  hashlink:
    on: push
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - name: Set up HashLink
        run: |
          Invoke-WebRequest https://github.com/HaxeFoundation/hashlink/releases/download/1.11/hl-1.11.0-win.zip -OutFile hashlink.zip
          Expand-Archive hashlink.zip
          Add-Content $Env:GITHUB_PATH (Resolve-Path hashlink/hl-1.11.0-win) -NoNewline
      - name: Check environment
        run: |
          haxe --version
          hl --version
      - name: Install dependencies
        run: haxelib install all --always
      - name: Run tests
        run: haxe hashlink.hxml
